package com.example.mokinvaraus_backend.models;

import jakarta.persistence.*;

/**
 * Class for Area entities.
 * <p>
 * Each area has their own entry in an appropriate table in the relational database. These entities represent those entries.
 */
@Entity
@Table(name = "location")
public class Alue {

    /**
     * Area's ID. Primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "location_id")
    private int areaId;

    /**
     * Area's name. Not to be confused with city or municipality.
     */
    @Column(name = "name")
    private String name;

    /**
     * Creates a new empty Alue instance.
     */
    public Alue() {
    }

    /**
     * Returns the area's ID. This is the unique primary key in the database table.
     * @return The ID of the area in integer.
     */
    public int getAreaId() {
        return areaId;
    }

    /**
     * Returns the area's name.
     * @return Name of the area in string.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name for the area.
     * @param name The name of the area, database accepts max. 40 character long string.
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "Alue{" +
                "areaId=" + areaId +
                ", name='" + name + '\'' +
                '}';
    }
}
