package com.example.mokinvaraus_backend.models;

import jakarta.persistence.*;

/**
 * Class for Customer entities.
 * <p>
 * Each customer has their own entry in an appropriate table in the relational database. These entities represent those entries.
 */
@Entity
@Table(name = "customer")
public class Asiakas {

    /**
     * Customer ID. Primary Key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "customer_id")
    private int customerId;

    /**
     * Customer's postal code.
     */
    @Column(name = "zip")
    private String postalCode;

    /**
     * Customer's first name.
     */
    @Column(name = "firstname")
    private String firstName;

    /**
     * CUstomer's last name.
     */
    @Column(name = "lastname")
    private String lastName;

    /**
     * Customer's address.
     */
    @Column(name = "address")
    private String streetAddress;

    /**
     * Customer's email address.
     */
    @Column(name = "email")
    private String email;

    /**
     * Customer's phone number.
     */
    @Column(name = "phone")
    private String phoneNumber;

    /**
     * Creates a new empty Asiakas object.
     */
    public Asiakas() {
    }

    /**
     * Returns the object's ID.
     * @return The customer's ID in integer.
     */
    public int getCustomerId() {
        return customerId;
    }

    /**
     * Returns the object's postal code field.
     * @return The customer's postal code in string.
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Returns the object's first name field.
     * @return The customer's first name in string.
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Returns the object's last name field.
     * @return The customer's last name in string.
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Returns the object's street address field.
     * @return The customer's street address in string.
     */
    public String getStreetAddress() {
        return streetAddress;
    }

    /**
     * Returns the object's email field.
     * @return The customer's email in string.
     */
    public String getEmail() {
        return email;
    }

    /**
     * Returns the object's phone number field.
     * @return The customer's phone number in string.
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the object's postal code field.
     * @param postalCode The customer's postal code in string.
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * Sets the object's first name field.
     * @param firstName The customer's first name in string.
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Sets the object's last name field.
     * @param lastName The customer's last name in string.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Sets the object's street address field.
     * @param streetAddress The customer's street address in string.
     */
    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress;
    }

    /**
     * Sets the object's email field.
     * @param email The customer's email in string.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Sets the object's phone number field.
     * @param phoneNumber The customer's phone number in string.
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Returns a string representation of the object, including all the fields and their contents.
     * @return A string representation of the object.
     */
    @Override
    public String toString() {
        return "Asiakas{" +
                "customerId=" + customerId +
                ", postalCode='" + postalCode + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", streetAddress='" + streetAddress + '\'' +
                ", email='" + email + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                '}';
    }
}
