package com.example.mokinvaraus_backend.models;

import jakarta.persistence.*;

import java.sql.Date;

import java.util.Set;

/**
 * Class for the Reservation Entities. All reservations are stored in an appropriate table in the database.
 */
@Entity
@Table(name = "reservation")
public class Varaus {

    /**
     * Reservation ID. Primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "reservation_id")
    private int reservationId;

    /**
     * ID of the customer that made the reservation. Foreign key from the customer table.
     */
    @Column(name = "customer_id")
    private int customerId;

    /**
     * ID of the cabin that was reserved. Foreign key from the cabin table.
     */
    @Column(name = "cabin_id")
    private int cabinId;

    /**
     * Date and time when the reservation was made. Stored in the database as datetime.
     */
    @Column(name = "reserved_date")
    private Date reservationDate;

    /**
     * Date and time when the reservation has been confirmed and the bill is sent. Stored in the database as datetime.
     */
    @Column(name = "confirmation_date")
    private Date reservationConfirmedDate;

    /**
     * Date and time when the reservation starts. Stored in the database as datetime.
     */
    @Column(name = "reservation_start")
    private Date reservationStartDate;

    /**
     * Date and time when the reservation ends. Stored in the database as datetime.
     */
    @Column(name = "reservation_end")
    private Date reservationEndDate;

    @OneToMany(mappedBy = "reservation")
    Set<VarauksenPalvelu> services;

    /**
     * Creates a new empty Varaus object.
     */
    public Varaus() {
    }

    /**
     * Returns the object's reservation ID field.
     * @return The reservation ID in int.
     */
    public int getReservationId() {
        return reservationId;
    }

    /**
     * Returns the object's customer ID field.
     * @return The customer ID in int.
     */
    public int getCustomerId() {
        return customerId;
    }

    /**
     * Returns the object's cabin ID field.
     * @return The cabin ID in int.
     */
    public int getCabinId() {
        return cabinId;
    }

    /**
     * Returns the object's reservation date field.
     * @return The reservation date in Date
     */
    public Date getReservationDate() {
        return reservationDate;
    }

    /**
     * Returns the object's reservation confirmed date field.
     * @return The reservation confirmed date in {@link java.sql.Date java.sql.Date} object.
     */
    public Date getReservationConfirmedDate() {
        return reservationConfirmedDate;
    }

    /**
     * Returns the object's reservation start date field.
     * @return The reservation start date in {@link java.sql.Date java.sql.Date} object.
     */
    public Date getReservationStartDate() {
        return reservationStartDate;
    }

    /**
     * Returns the object's reservation end date field.
     * @return The reservation end date in {@link java.sql.Date java.sql.Date} object.
     */
    public Date getReservationEndDate() {
        return reservationEndDate;
    }

    /**
     * Sets the object's reservation ID field.
     * @param reservationId The reservation ID in int.
     */
    public void setReservationId(int reservationId) {
        this.reservationId = reservationId;
    }

    /**
     * Sets the object's reservation ID field.
     * @param customerId The customer's ID in int.
     */
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    /**
     * Sets the object's cabin ID field.
     * @param cabinId The ID of the reserved cabin in int.
     */
    public void setCabinId(int cabinId) {
        this.cabinId = cabinId;
    }

    /**
     * Sets the object's reservation date field.
     * @param reservationDate The reservation date in {@link java.sql.Date java.sql.Date} object.
     */
    public void setReservationDate(Date reservationDate) {
        this.reservationDate = reservationDate;
    }

    /**
     * Sets the object's reservation confirmed date field.
     * @param reservationConfirmedDate The reservation confirmed date in {@link java.sql.Date java.sql.Date} object.
     */
    public void setReservationConfirmedDate(Date reservationConfirmedDate) {
        this.reservationConfirmedDate = reservationConfirmedDate;
    }

    /**
     * Sets the object's reservation start date field.
     * @param reservationStartDate The reservation start date in {@link java.sql.Date java.sql.Date} object.
     */
    public void setReservationStartDate(Date reservationStartDate) {
        this.reservationStartDate = reservationStartDate;
    }

    /**
     * Sets the object's reservation end date field.
     * @param reservationEndDate The reservation end date in {@link java.sql.Date java.sql.Date} object.
     */
    public void setReservationEndDate(Date reservationEndDate) {
        this.reservationEndDate = reservationEndDate;
    }

    /**
     * Returns a string representation of the Varaus object.
     *
     * @return  A string representation of the Varaus object.
     */
    @Override
    public String toString() {
        return "Varaus{" +
                "reservationId=" + reservationId +
                ", customerId=" + customerId +
                ", cabinId=" + cabinId +
                ", reservationDate=" + reservationDate +
                ", reservationConfirmedDate=" + reservationConfirmedDate +
                ", reservationStartDate=" + reservationStartDate +
                ", reservationEndDate=" + reservationEndDate +
                '}';
    }
}
